<?php
/**
 * OuterIterator 类
 * Programmer:SuperProgrammer_YXQ
 * Date:2020/9/11
 * Time:10:58
 */
class OuterImpl extends IteratorIterator
{
    public function current()
    {
        return parent::current().'_'.rand(1,999999); // TODO: Change the autogenerated stub
    }
    public function key()
    {
        return parent::key().'_'.rand(10,99); // TODO: Change the autogenerated stub
    }
}


$array = array('value1','value2','value3','value4','value5','value6');

$outer = new OuterImpl(new ArrayIterator($array));

foreach ($outer as $key => $value)
{
    echo '++'.$key.'-'.$value."\n";
}